seed: 42
device: cpu
num_trainer: 2
num_env_per_trainer: 5

exp_name: pretrain_push
out_folder: result/${exp_name}
data_folder: ${out_folder}/data
agent: AdaptTrainer
eval: False
task: Push

wandb:
  entity:
  project:
  name: ${exp_name}

env:
  render: False
  name: PushOverlap
  max_train_steps: 1
  max_eval_steps: 1
  action_dim: 2 # vel_x, yaw
  camera:
  dt: 0.01
  specific:
    vel_x_range: [0.3, 0.8]
    yaw_range: [-0.3, 0.3]
    goal_x_range: [0.7, 1.0]
    goal_y_range: [-0.1, 0.1]

adapt:
  max_itr: 1
  num_adapt_init: 10000
  num_adapt: 0
  init_inference_update_wait: 100
  inference_update_freq: 10
  num_adapt_step: 10
  replay_ratio: 16
  batch_size: 64
  eval_freq: 48
  twin_threshold: 0.16  # 8% in each of the four dimensions
  lifetime_threshold: 1
  reward_threshold: 0.8
  spawn:
    num_particle_init: 8
    num_particle: 0
    inner_perturbation: 0.025
    meta_perturbation: 0.05
    kill_freq:
    reward_threshold:
  num_meta_target_task: 24
  num_inner_target_task: 24
  num_task_train: 96
  num_meta_test_task: 24
  eps_init:
    init: 1.0
    period: 1000
    end: 0.1
    step: -0.1  # always use small step
  eps:  # not used in pretrain
    init: 0.5
    period: 10
    end: 0.1
    step: -0.1
  meta_policy_option: reuse
  inner_policy_option: reuse

inference:
  seed: ${seed}
  device: ${device}
  eval: ${eval}
  memory_capacity: 10000
  lr_c: 0.0003
  lr_c_schedule: false
  tau: 0.01
  single_step: False
  gamma: 0.9
  #
  num_feature: 16  # 4 obs
  arch:
    state_only: True
    skip_dim: 0
    mlp_dim:
      critic: [128, 128]
    append_dim:
      critic: 0
    critic_path:

util:
  name: ${task}
  seed: ${seed}
  target_obs: final_T_plus_goal
  reward_scaling: raw
  num_episode_for_obs: 4
  obs_lb: [0.6, -0.2, 0.7, -0.1]  # final T and goal
  obs_ub: [1.2, 0.2, 1.0, 0.1]

policy:
  name: Value
  seed: ${seed}
  device: ${device}
  out_folder: ${data_folder}/policy
  num_env: ${num_env_per_trainer}
  action_dim: ${env.action_dim}
  max_steps_train: ${env.max_train_steps}
  max_steps_eval: ${env.max_eval_steps}
  eval: ${eval}
  target_eval_reward: 0.95
  #
  # init_max_sample_steps: 10000
  # max_sample_step_decay: 2000
  # max_sample_step_min: 2000
  init_max_sample_steps: 100
  max_sample_step_decay: 20
  max_sample_step_min: 20
  #
  num_warmup_step_percentage: 0.2
  # num_eval_episode: 48
  num_eval_episode: 5
  memory_capacity: 5000 # keep all samples; not re-using memory
  # update_freq: 48
  update_freq: 10
  replay_ratio: 16
  # batch_size: 64
  batch_size: 4
  # check_freq: 5
  check_freq: 1
  #
  save_top_k: 1
  eps:  # not used
    init: 1.0
    period_percentage: 0.1
    end: 0.5
    step: -0.1
  learner:
    name: NAF
    seed: ${seed}
    action_dim: ${env.action_dim}
    eval: ${eval}
    device: ${device}
    noise_scale: 0.1
    update_period: 1
    lr_c: 0.001 # high
    lr_c_schedule: False
    tau: 0.01
    single_step: True
    arch:
      state_only: True
      input_dim: 2  # goal
      mlp_dim:
        critic:
          - 64
          - 2
      append_dim: 
        critic: 0 # no belief
      use_ln: False
  utility:
    name: Dummy
    device: ${device}

param:
  name: ${task}
  seed: ${seed}
  device: ${device}
  data_path: ${data_folder}
  num_param_bin_for_continuous: 3
  sample_ood_full_width_fraction: 1.0
  param:
    OBJ_MU:
      dist: gaussian
      step: 0.1
      minimum: 0.05
      maximum: 0.20
      init_std: 0.0001
      min_std: 0.0001
      max_std: 0.0001
      fixed: false
    OBJ_MODULUS:
      dist: gaussian
      step: 0.1
      minimum: 4
      maximum: 6
      init_std: 0.0001
      min_std: 0.0001
      max_std: 0.0001
      fixed: false
    OVERLAP_MU:
      dist: gaussian
      step: 0.1
      minimum: 0.20 # big range
      maximum: 0.80
      init_std: 0.0001
      min_std: 0.0001
      max_std: 0.0001
      fixed: false
    OVERLAP_Y:
      dist: gaussian
      step: 0.1
      minimum: -0.1
      maximum: 0.1
      init_std: 0.0001
      min_std: 0.0001
      max_std: 0.0001
      fixed: false
    OBJ_COM_X:
      dist: uniform
      range:
        - 0
        - 0
      minimum: 0
      maximum: 0
      fixed: true
    OBJ_COM_Y:
      dist: uniform
      range:
        - 0
        - 0
      minimum: 0
      maximum: 0
      fixed: true
  goal:
    radius_range: # added to 0.45, [0.70, 1.00]
      - 0.25
      - 0.55
    yaw_range:
      - -0.175  # 10 degrees
      - 0.175

param_target:
  seed: ${seed}
  device: ${device}
  data_path: ${data_folder}
  param:
    OBJ_MU:
      dist: uniform
      range:
        - 0.10
        - 0.10
      fixed: true
    OBJ_MODULUS:
      dist: uniform
      range:
        - 4.0
        - 4.0
      fixed: true
    OVERLAP_MU:
      dist: uniform
      range:
        - 0.5
        - 0.5
      fixed: true
    OVERLAP_Y:
      dist: uniform
      range:
        - 0
        - 0
      fixed: true
    OBJ_COM_X:
      dist: uniform
      range:
        - 0
        - 0
      fixed: true
    OBJ_COM_Y:
      dist: uniform
      range:
        - 0
        - 0
      fixed: true